### ISSUE TITLE
Significantly reduces snappiness of opening files for editing using :e

### ISSUE THREAD

**Issue by cyphactor** [tpope/vim-rake#27]

**Comment by tpope** [comment]
Gonna need a lot more to go on than that. For me it adds about 20ms.

**Comment by cyphactor** [comment]
Did some digging and it is specifically the filetype plugin on call which is causing it to be slow if that helps.

**Comment by tpope** [comment]
Yes, that tells me it's an issue with `ftplugin/ruby.vim` from vim-ruby. There's lots of stuff in that file you could try commenting out if you want to debug further.
