### ISSUE TITLE
Activate Rake.vim when Rails.vim will not

### ISSUE THREAD

**Issue by avdgaag** [tpope/vim-rake#28]
See https://github.com/tpope/vim-rails/issues/391, where Rails.vim activation was limited to avoid false positives with https://github.com/lotus/lotus projects. As far as I can tell, Rake.vim contains the same code in reverse, NOT activating for projects that look like Rails apps, so as not to conflict with Rails.vim. So, I guess now Rake.vim needs to be updated so it _will_ activate for such projects.

Let me know if you agree with this idea and if you want me to take a stab at making a pull request.

**Comment by tpope** [comment]
Yep sounds good.
