### ISSUE TITLE
Support for Ranges

### ISSUE THREAD

**Issue by dhruvasagar** [tpope/vim-rake#3]
Hi, the rails Rake supports ranges, I can use :.Rake to run just the current test, please bring that support to this as well.

**Comment by teoljungberg** [comment]
I just ran into this, and was surprised that it worked with `vim-rails` but not with `vim-rake`.

Has there been any development on this issue?

**Comment by tpope** [comment]
Dispatch has line number support now with a `` `=...` `` expression keyed off of `v:lnum`. I haven't investigated tapping into it in rake.vim.

**Comment by teoljungberg** [comment]
If I can be pointed towards some documentation for this, and where to start, I'd gladly take a crack at resolving this. I'm unsure how much more efficient that will be compared to someone who has the solution mapped out, but I don't shy away from learning.

**Comment by tpope** [comment]
There's no explicit dispatch.vim documentation, but see ``:h `=``. Generally, you will use something like `` `=v:lnum ? ':'.v:lnum : ''` ``. You probably just need to change [this line](https://github.com/tpope/vim-rake/blob/c38ed340c43ad82b148001f97c61520adaf40ef5/plugin/rake.vim#L155) for the RSpec side of things.

**Comment by teoljungberg** [comment]
This could be closed now since #32 is merged.
