### ISSUE TITLE
Go file should work like it works in rails projects

### ISSUE THREAD

**Issue by hiukkanen** [tpope/vim-rake#30]
<kbd>gf</kbd> does not work as well as it works on rails projects.

When word `Admin` is under cursor in a line like

    module Admin

<kbd>gf</kbd> tries to open Admin.rb and fails miserably. This seems to come from ftplugin/ruby.vim shipped with vim. When editing similar file in rails project <kbd>gf</kbd> calls RailsFind from rais.vim.

<kbd>gf</kbd> should work in any ruby project like it works in rails projects.

**Comment by tpope** [comment]
The very latest [vim-ruby](/vim-ruby/vim-ruby) (which is what ships with Vim) is smarter about this.
