### ISSUE TITLE
Plugin overwrites makeprg

### ISSUE THREAD

**Issue by promisedlandt** [tpope/vim-rake#31]
Hello,

in my .vimrc I have `autocmd FileType ruby set makeprg=rspec\ --format\ documentation` (to work with the rspec compiler from ruby.vim).

However, if I add rake.vim, makeprg will be set to `bundle exec rake` instead.
[here](https://github.com/tpope/vim-rake/blob/master/plugin/rake.vim#L236) / [here](https://github.com/tpope/vim-rake/blob/master/plugin/rake.vim#L242) seem to be the offenders.

As I know almost not vimscript - is it possible to add a configuration option to not overwrite `makeprg`? 
Or only set it when running `:Rake`? That looked to me like the intent anyway.

Edit: Actually, it appears as though `compiler` is not correctly reset. If I manually run `compiler rspec`, everything works as expected.

**Comment by tpope** [comment]
You can force your own `'makeprg'` by setting the `"make"` key in a custom Projectionist config.
