### ISSUE TITLE
Expand `=

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-rake#33]
With the introduction of #32, we are tacking on the current line numner to the RSpec tests with `=.

However, `:Focus` and `:.Focus` are not returning what `:Dispatch` or `:.Dispatch` will actually run.

This issue is about changing it from

```
Buffer default is :Dispatch -dir=/path/to/project bin/rspec /path/to/project/spec/whatever_spec.rb`=v:lnum ? ":".v:lnum : ""`
```

Into this for `:Focus`:

```
Buffer default is :Dispatch -dir=/path/to/project bin/rspec /path/to/project/spec/whatever_spec.rb
```

or this when `:10Focus` is given:

```
Buffer default is :Dispatch -dir=/path/to/project bin/rspec /path/to/project/spec/whatever_spec.rb:10
```

The naive approach I found is to leverage `expand()` in vim-dispatch's `dispatch#focus` or `dispatch#focus_command` functions to expand the proposed dispatch into what it will actually run.

Before I or someone else open a PR for this functionallity - I'd like to discuss it before to see if this is feature / functionallity is wanted.

**Comment by tpope** [comment]
`:Focus` deliberately reveals that there's some cleverness going on. `:.Focus` and `:0Focus` should do what you expect.

**Comment by teoljungberg** [comment]
And they both do. I wanted to see if there was any interest in expanding `:Focus` to do the same.
