### ISSUE TITLE
Unable to run tests with dispatch.vim

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-rake#36]
When I run `:Dispatch` in a small ruby project - I'm prompted with the following error messages:

```
Failure: !bin/rspec /absolute/path/to/project/file_spec.rb%:s/.*/\=exists("l#") ? ":".l# : ""//absolute/path/to/project/ (sync/?)
```

And my quickfix list only contains:

```
zsh:1: number expected
```

By doing a quick bisect, this was introduced in db81f137da4df80c4ee13d51a99698f565260d95 with the new dispatch.vim line syntax.

I'm on the latest version of both rake.vim and dispatch.vim.

Resetting to c74cf8f52d5f896e13749ff358a39a87a0604617 makes rake.vim and dispatch.vim play nicely together.

**Comment by tpope** [comment]
This was a Projectionist bug stacked on top of failing to handle the no line number case correctly.

**Comment by teoljungberg** [comment]
Thank you! `:.Dispatch` still doesn't work, probably something related.

Also, this test command doesn't look just right, why is the directory root being added to the Dispatch command?

```
!bin/rspec /absolute/path/to/project/file_spec.rb /absolute/path/to/project (tmux/75141)
```

**Comment by teoljungberg** [comment]
I did a naive fix for running a single test:

```diff
diff --git a/plugin/rake.vim b/plugin/rake.vim
index e423802..666211f 100644
--- a/plugin/rake.vim
+++ b/plugin/rake.vim
@@ -173,7 +173,7 @@ function! s:ProjectionistDetect() abort
         let projections['test/*.rb'] = {'dispatch': ruby . ' -Itest {file}'}
       endif
       let projections['spec/*_spec.rb'].dispatch =
-            \ s:binstub(real_root, 'rspec') . ' {file}%:s/.*/\=exists("l#") ? ":".l# : " "/{vim|nothing}'
+            \ s:binstub(real_root, 'rspec') . ' {file}%:s/.*/\=exists("l#") ? ":".l#. " " : " "/{vim|nothing}'
     endif
     call filter(projections['lib/*.rb'].alternate, 'get(l:, v:val[0:3])')
     call filter(projections, 'v:key[4] !=# "/" || get(l:, v:key[0:3])')
```

Having the absolute path appended after the test to run makes running a single test impossible, as the entire test suite will be run regardless.

I ran the same command as described above:

```
!bin/rspec /absolute/path/to/project/file_spec.rb:10 /absolute/path/to/project
```

With the following output from the quickfix list:

```
|| Run options: include {:locations=>{"./spec/file_spec.rb"=>[10]}}
|| 
|| Randomized with seed 37647
|| ..............................................................
|| 
|| Finished in 0.31346 seconds (files took 0.70886 seconds to load)
|| 62 examples, 0 failures
|| 
|| Randomized with seed 37647
|| 
```

Where I would expect that it should only run the tests on line 10.

**Comment by tpope** [comment]
Looks like you didn't update Projectionist.

**Comment by teoljungberg** [comment]
Ah! I did miss that.

Thank you, Tim!
