### ISSUE TITLE
vim-rake conflicting with new versions of multiple plugins

### ISSUE THREAD

**Issue by lordkage** [tpope/vim-rake#37]
I am recently updated my plugins on my home laptop to all current, and `vim-rake` caused a bunch or errors.

Upon issuing `vim` in an existing project/repo:
```
Error detected while processing function <SNR>57_project_ruby_include_path:
line    6:
E484: Can't open file /var/folders/7x/jmvtwc388xj8xw001s76t54h0000gn/T/vE0JmfA/1
Press ENTER or type command to continue
Error detected while processing function <SNR>57_Setup:
line    3:
E171: Missing :endif
Press ENTER or type command to continue
```
Upon issuing a `:q`:
```
Error detected while processing BufLeave Auto commands for "NERD_tree_*":
E121: Undefined variable: b:NERDTree
Press ENTER or type command to continue
```

At the minimum, I was able to confirm it conflicts with
 - `scrooloose/nerdtree`
 - `tpope/vim-rails`

**Comment by tpope** [comment]
The stack trace points to https://github.com/tpope/vim-rake/blob/3beb1504493931da4405a1aac5f2f42b1e9ee554/plugin/rake.vim#L245, which suggests an issue shelling out. What is the output of `:set shell?`?

**Comment by lordkage** [comment]
The output says `shell=/bin/tcsh`, which isn't right... This appears to be how I setup my bash profile with iTerm2. 😭

However, the "default" profile, which is tcsh, still throws the error inside ruby related projects. I am guessing I have diverged on my paths between my two rc scripts.

Thank you for the push in the right direction.
